### ISSUE TITLE
importing PygameShader when running script directly causes error: "no module named gaussianblur5x5" 

### ISSUE THREAD

**Issue by SkysurferKon** [yoyoberenguer/PygameShader#1]

**Comment by yoyoberenguer** [comment]
Hi SkysurferKon,

Thank you for taking the time to report an issue.

Can you show me an example of scrip causing this issue ?
Do you mean that an error is thrown as soon as you are import the library ? 
Also if you could provide the python version used and the platform (windows ?)

To use the Gaussian blur you would normally import the method shader_blur5x5_array24_inplace from 
the library such as:
After installing the library using PIP from the command line : 
C:\>pip install PygameShader

In Python : 
import PygameShader 
from PygameShader import shader_blur5x5_array24_inplace

OR 
# To load all the methods from the library
import PygameShader
from PygameShader import *

**Comment by yoyoberenguer** [comment]
.

**Comment by SkysurferKon** [comment]
Thanks for writing this detailed explanation! Is PygameShader compatible with a PyInstaller "--onefile" exe file?

**Comment by yoyoberenguer** [comment]
Hi, 
If you are looking for an automatic installer, the best way to install this library is to use the well known 
```dos 
pip install PygameShader==1.0.4
```
If you are a bit more adventurous you can also download the git source code and compile the library from source

But to answer your question regarding the PyInstaller program ,  I would say yes, PygameShader is compatible with PyInstaller even though I never tried to use PyInstaller since this is a cython/python library that does not include any hook file but uses an external library that load with an import statement

I used PyInstaller in the past for various project including project with C & Cython & python codes and would generate an executable file. In order to create a single file you would have to tweak and configure PyInstaller to know where to find all the source code, binaries and images that needs to be attached to the executable.

**Comment by yoyoberenguer** [comment]
Another utility that could perform the same task would be to use the great program call `Inno Setup`. This will do the same and build an executable file containing all the directories and source code etc. The advantage of `Inno setup` is to be able to de-install the project as you would normally do for commercial programs.
